# Generated by Django 3.1.7 on 2021-03-24 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.TextField()),
                ('message', models.CharField(max_length=100)),
                ('send_date', models.DateTimeField(default=datetime.datetime(2021, 3, 24, 16, 11, 27, 907021, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
